package review_test

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/WilsonSousajr/omatty/internal/registry"
	"github.com/WilsonSousajr/omatty/internal/review"
)

// The built-in list is the third and last of #338's detections, and the one
// that must be short: a wrong yes hides a file somebody needed to read.
func TestGeneratedName_KnowsTheUsualSuspects_issue338(t *testing.T) {
	generated := []string{
		"go.sum", "package-lock.json", "pnpm-lock.yaml", "yarn.lock",
		"Cargo.lock", "poetry.lock", "composer.lock", "Gemfile.lock",
		"api/schema.pb.go", "internal/ui/mock_store.generated.go",
		"web/types.generated.ts", "build/bundle.js", "dist/app.css",
		"coverage/lcov.info", "vendor/github.com/x/y.go",
		"node_modules/left-pad/index.js",
		// The two that are never hand-written at any depth.
		"web/app/node_modules/x/index.js", "cmd/tool/vendor/x/y.go",
	}
	for _, path := range generated {
		if !review.GeneratedName(path) {
			t.Errorf("GeneratedName(%q) = false, want true", path)
		}
	}
}

// The other half of a short list: everything it must not claim. go.mod beside
// go.sum is the pair that matters - one is written by a person, one is not.
func TestGeneratedName_ClaimsNothingElse_issue338(t *testing.T) {
	handWritten := []string{
		"go.mod", "README.md", "internal/ui/model.go", "Makefile",
		".github/workflows/ci.yml", "docs/ROADMAP.md", "scripts/check-crap.sh",
		// Named for the thing, not generated by it.
		"internal/review/generated.go", "internal/review/generated_test.go",
		"cmd/omatty/main.go", "testdata/fake-claude",
		// A directory whose name merely contains a suspect one.
		"buildkite/pipeline.yml", "distributed/queue.go", "vendored/notes.md",
		// Found by running this against omatty itself: an output directory's
		// name is a perfectly good package name, so the rule is root-relative.
		// internal/coverage is hand-written source, and folding it away hid a
		// package from review.
		"internal/coverage/blocks.go", "internal/coverage/coverage.go",
		"src/build/helper.go", "app/dist/notes.md",
	}
	for _, path := range handWritten {
		if review.GeneratedName(path) {
			t.Errorf("GeneratedName(%q) = true, want false: a wrong yes hides a file "+
				"somebody has to read", path)
		}
	}
}

// The second detection: the Go convention, which is a specific line and not
// the word "generated" appearing somewhere.
func TestGeneratedHeader_MatchesTheGoConventionOnly_issue338(t *testing.T) {
	yes := []string{
		"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n",
		"// Code generated by mockery v2.42.0. DO NOT EDIT.\npackage mocks\n",
		"//go:build !test\n\n// Code generated by stringer. DO NOT EDIT.\npackage x\n",
	}
	for _, head := range yes {
		if !review.GeneratedHeader([]byte(head)) {
			t.Errorf("GeneratedHeader(%q) = false, want true", head)
		}
	}

	no := []string{
		"// This file was generated, do not edit it\npackage x\n",
		"// Code generated by hand\npackage x\n",
		"package x\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\n",
		"",
	}
	for _, head := range no {
		if review.GeneratedHeader([]byte(head)) {
			t.Errorf("GeneratedHeader(%q) = true, want false", head)
		}
	}
}

// Source.Generated is the three detections in the order #338 asks for, over
// the paths a caller names.
func TestSourceGenerated_AsksGitFirstThenTheNameThenTheHeader_issue338(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "hand.go", "package hand\n")
	writeFile(t, dir, "stringer.go", "// Code generated by stringer. DO NOT EDIT.\npackage x\n")
	writeFile(t, dir, "go.sum", "example.com v1.0.0 h1:abc=\n")
	writeFile(t, dir, "declared.md", "# whatever\n")

	git := &FakeGit{AttrOut: map[string]bool{"declared.md": true}}
	sess := registry.Session{ID: "s1", Dir: dir}

	got, err := review.NewSource(git).Generated(sess, []string{"hand.go", "stringer.go", "go.sum", "declared.md"})
	if err != nil {
		t.Fatal(err)
	}

	for path, want := range map[string]bool{
		"declared.md": true, "go.sum": true, "stringer.go": true, "hand.go": false,
	} {
		if got[path] != want {
			t.Errorf("Generated[%q] = %v, want %v", path, got[path], want)
		}
	}
}

// The header read is bounded and the file may not be there at all - a deleted
// file is in the diff and gone from the worktree. Neither is an error: the
// answer is simply "not generated by its header".
func TestSourceGenerated_AMissingFileIsNotAnError_issue338(t *testing.T) {
	git := &FakeGit{}
	sess := registry.Session{ID: "s1", Dir: t.TempDir()}

	got, err := review.NewSource(git).Generated(sess, []string{"deleted.go"})
	if err != nil {
		t.Fatalf("a file that is not on disk must not fail the detection: %v", err)
	}
	if got["deleted.go"] {
		t.Error("a file that could not be read was reported generated")
	}
}

// git failing is an error the caller decides about, not a silent "nothing is
// generated": that would hide the coverage exclusion too.
func TestSourceGenerated_ReportsGitFailing_issue338(t *testing.T) {
	git := &FakeGit{Errs: map[string]error{"Attr": errors.New("git is unwell")}}

	_, err := review.NewSource(git).Generated(registry.Session{ID: "s1", Dir: t.TempDir()}, []string{"a.go"})
	if err == nil {
		t.Error("Generated swallowed a git failure")
	}
}

func writeFile(t *testing.T, dir, rel, body string) {
	t.Helper()
	path := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

// The header read is Go-only, and that is a stated limit rather than an
// oversight: a tree is re-listed at every turn end, so opening every file in a
// repository to look for a Go comment is a cost paid repeatedly for an answer
// that cannot apply. Another language's generated file is reached by its name
// or by the repository's own linguist-generated.
func TestSourceGenerated_TheHeaderReadIsGoOnly_issue338(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "schema.ts", "// Code generated by openapi. DO NOT EDIT.\nexport type A = 1\n")

	got, err := review.NewSource(&FakeGit{}).Generated(registry.Session{ID: "s1", Dir: dir}, []string{"schema.ts"})
	if err != nil {
		t.Fatal(err)
	}
	if got["schema.ts"] {
		t.Error("a .ts file was sniffed for the Go convention; the read is meant to be Go-only")
	}
}
