// Which of a session's files nobody wrote (#338): lockfiles, protobuf output,
// build and coverage directories. They sit in the review queue beside source
// today, and M10's coverage markers make one look worse than it is - it has no
// test, and never will.

package review

import (
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/WilsonSousajr/omatty/internal/registry"
)

// generatedAttr is the attribute a repository declares its own generated files
// with. GitHub's linguist defines it and every forge-aware tool reads it, so it
// is the one declaration a project has probably already made.
const generatedAttr = "linguist-generated"

// headBytes is how much of a file is read looking for the Go convention. The
// marker belongs at the top by the convention's own definition, and reading
// more of every changed file to find a line that would not count is a cost
// with no answer attached.
const headBytes = 4 << 10

// goGenerated is the Go convention, which is a whole line and a specific one.
// `^// Code generated .* DO NOT EDIT\.$` is what the toolchain documents, and
// matching anything looser - a comment that merely says "generated" - would
// hide hand-written files that describe generated ones.
var goGenerated = regexp.MustCompile(`(?m)^// Code generated .* DO NOT EDIT\.$`)

// packageClause is where a Go file stops being a header.
var packageClause = regexp.MustCompile(`(?m)^package `)

// generatedNames are the files whose name is the evidence.
var generatedNames = map[string]bool{
	"go.sum": true, "package-lock.json": true, "pnpm-lock.yaml": true,
	"yarn.lock": true, "Cargo.lock": true, "poetry.lock": true,
	"composer.lock": true, "Gemfile.lock": true, "uv.lock": true,
	"Pipfile.lock": true, "flake.lock": true, "bun.lockb": true,
}

// generatedRootDirs are output directories, matched only at the root of the
// repository.
//
// Only at the root, and this is the correction that matters: `coverage` and
// `build` are perfectly good package names, and omatty's own
// `internal/coverage/blocks.go` is hand-written source. A rule that matched
// them at any depth folded a package away - the exact "wrong yes hides a file
// somebody had to read" this list's own comment warns about. Orca's rule is
// spelled `/coverage/` for the same reason.
var generatedRootDirs = map[string]bool{
	"build": true, "dist": true, "coverage": true, "target": true, "out": true,
}

// generatedAnyDirs are the two that are never hand-written at any depth: a
// dependency tree is a dependency tree wherever it sits, and a monorepo has one
// per package.
var generatedAnyDirs = map[string]bool{"node_modules": true, "vendor": true}

// generatedSuffixes are the name shapes a generator leaves behind.
var generatedSuffixes = []string{".pb.go", ".pb.gw.go", "_pb2.py", ".g.dart"}

// GeneratedName reports whether path's name alone says nobody wrote it.
//
//	review.GeneratedName("go.sum")             // true
//	review.GeneratedName("go.mod")             // false
//
// Deliberately short, and the list only shrinks arguments rather than settling
// them: a wrong yes hides a file somebody had to read, which costs more than
// the several right ones gain. `pair.go` makes the same argument for its own
// lists. Anything not on it falls through to the repository's own declaration
// and to the file's header, which are both better evidence than a guess.
func GeneratedName(p string) bool {
	if generatedNames[path.Base(p)] {
		return true
	}
	dirs := strings.Split(path.Dir(p), "/")
	if generatedRootDirs[dirs[0]] {
		return true
	}
	for _, dir := range dirs {
		if generatedAnyDirs[dir] {
			return true
		}
	}
	return generatedShape(path.Base(p))
}

// generatedShape reads a name for a generator's fingerprint.
func generatedShape(name string) bool {
	if strings.Contains(name, ".generated.") {
		return true
	}
	for _, suffix := range generatedSuffixes {
		if strings.HasSuffix(name, suffix) {
			return true
		}
	}
	return false
}

// GeneratedHeader reports whether head carries the Go convention's marker.
//
//	review.GeneratedHeader([]byte("// Code generated by protoc. DO NOT EDIT.\n"))
func GeneratedHeader(head []byte) bool {
	line := goGenerated.FindIndex(head)
	if line == nil {
		return false
	}
	// The convention puts the marker before the package clause. A file that
	// says it further down is describing generated code, not generated by
	// anything - `internal/review/generated.go` would otherwise hide itself.
	// The clause is matched at the start of a line, because the first line of
	// a file has no newline in front of it.
	return !packageClause.Match(head[:line[0]])
}

// Generated is which of paths are generated, in #338's order: what the
// repository declares, then the name, then the file's own header.
//
//	gen, err := src.Generated(sess, changedPaths)
//
// The declaration comes first because it is the only one that cannot be wrong:
// the project said so. The header read is last because it costs a file open,
// and it is skipped entirely for anything the first two already answered.
func (s *Source) Generated(sess registry.Session, paths []string) (map[string]bool, error) {
	declared, err := s.git.Attr(sess.Dir, generatedAttr, paths)
	if err != nil {
		return nil, fmt.Errorf("review: reading %s in %q: %w", generatedAttr, sess.Dir, err)
	}
	out := make(map[string]bool, len(paths))
	for _, p := range paths {
		out[p] = declared[p] || GeneratedName(p) || (sniffable(p) && headerSays(sess.Dir, p))
	}
	return out, nil
}

// sniffable bounds the header read to the files the convention belongs to.
//
// `// Code generated ... DO NOT EDIT.` is Go's convention, defined by the Go
// toolchain, and a tree is listed again at every turn end - so opening every
// file in a repository to look for a Go comment would be a cost paid over and
// over for an answer that cannot apply. A generated file in another language is
// reached by its name or by the repository's own `linguist-generated`, which are
// both better evidence and cost nothing per file.
func sniffable(p string) bool { return strings.HasSuffix(p, ".go") }

// headerSays reads the first headBytes of a file and asks GeneratedHeader.
//
// A file that cannot be read is not generated: a deleted file is in the diff
// and gone from the worktree, and an unreadable one is the operator's business
// rather than this detection's. Either way the honest answer is "the header did
// not say so", never an error that would take the whole listing down with it.
func headerSays(dir, rel string) bool {
	f, err := os.Open(filepath.Join(dir, rel))
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	head, err := io.ReadAll(io.LimitReader(f, headBytes))
	if err != nil {
		return false
	}
	return GeneratedHeader(head)
}
