package fsread_test

import (
	"path/filepath"
	"testing"

	"github.com/WilsonSousajr/omatty/internal/infra/fsread"
)

// The sniff reads only the head it asks for, and a file that is not there is
// an error for the caller to read as "the header did not say so" (#338, #653).
func TestHead_readsAtMostTheLimit_issue653(t *testing.T) {
	dir := t.TempDir()
	mustWrite(t, filepath.Join(dir, "a.go"), "// Code generated by x. DO NOT EDIT.\npackage a\n")

	head, err := fsread.Head(dir, "a.go", 7)

	if err != nil || string(head) != "// Code" {
		t.Errorf("Head = %q, %v; want the first 7 bytes", head, err)
	}
	if _, err := fsread.Head(dir, "gone.go", 7); err == nil {
		t.Error("Head of a missing file returned no error")
	}
}
