package review_test

import (
	"testing"

	"github.com/WilsonSousajr/omatty/internal/domain/review"
)

// parsed holds every diff these tests build, already parsed by
// the real ParseDiff (migration step 3.6a, #635), which wraps go-gitdiff and
// lives in internal/infra/gitdiff. Calling it from here would make
// domain/review_test -> gitdiff -> domain/review, the test-graph cycle
// check-deps refuses. The literals are generated, never edited: infra/gitdiff's
// parsed_generate_test.go writes them, and its parsed_guard_test.go fails the
// moment ParseDiff stops producing them.
var parsed = map[string]review.Diff{
	"diff --git a/a.go b/a.go\nindex 1111111..2222222 100644\n--- a/a.go\n+++ b/a.go\n@@ -10,3 +10,3 @@ func f() {\n \ta := 1\n-\tb := 2\n+\tb := 3\n }\n":                                                                                                                                                                                                                                                   review.Diff{Files: []review.File{review.File{Path: "a.go", OldPath: "a.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -10,3 +10,3 @@ func f() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 10, NewNo: 10}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 11, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 3", OldNo: 0, NewNo: 11}, review.Line{Kind: 0, Text: "}", OldNo: 12, NewNo: 12}}}}}}},
	"diff --git a/a.go b/a.go\nindex 1111111..2222222 100644\n--- a/a.go\n+++ b/a.go\n@@ -10,3 +10,3 @@ func f() {\n \ta := 1\n-\tb := 2\n+\tb := 4\n }\n":                                                                                                                                                                                                                                                   review.Diff{Files: []review.File{review.File{Path: "a.go", OldPath: "a.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -10,3 +10,3 @@ func f() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 10, NewNo: 10}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 11, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 4", OldNo: 0, NewNo: 11}, review.Line{Kind: 0, Text: "}", OldNo: 12, NewNo: 12}}}}}}},
	"diff --git a/a.go b/a.go\nindex 1111111..2222222 100644\n--- a/a.go\n+++ b/a.go\n@@ -40,3 +41,3 @@ func f() {\n \ta := 1\n-\tb := 2\n+\tb := 3\n }\n":                                                                                                                                                                                                                                                   review.Diff{Files: []review.File{review.File{Path: "a.go", OldPath: "a.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -40,3 +41,3 @@ func f() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 40, NewNo: 41}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 41, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 3", OldNo: 0, NewNo: 42}, review.Line{Kind: 0, Text: "}", OldNo: 42, NewNo: 43}}}}}}},
	"diff --git a/f.go b/f.go\nindex 1111111..2222222 100644\n--- a/f.go\n+++ b/f.go\n@@ -1 +1,5 @@\n package f\n+func a() {\n+}\n+func b() {\n+}\n":                                                                                                                                                                                                                                                         review.Diff{Files: []review.File{review.File{Path: "f.go", OldPath: "f.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -1,1 +1,5 @@", Lines: []review.Line{review.Line{Kind: 0, Text: "package f", OldNo: 1, NewNo: 1}, review.Line{Kind: 1, Text: "func a() {", OldNo: 0, NewNo: 2}, review.Line{Kind: 1, Text: "}", OldNo: 0, NewNo: 3}, review.Line{Kind: 1, Text: "func b() {", OldNo: 0, NewNo: 4}, review.Line{Kind: 1, Text: "}", OldNo: 0, NewNo: 5}}}}}}},
	"diff --git a/f.go b/f.go\nindex 3333333..2222222 100644\n--- a/f.go\n+++ b/f.go\n@@ -1,3 +1,5 @@\n package f\n func a() {\n }\n+func b() {\n+}\n":                                                                                                                                                                                                                                                       review.Diff{Files: []review.File{review.File{Path: "f.go", OldPath: "f.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -1,3 +1,5 @@", Lines: []review.Line{review.Line{Kind: 0, Text: "package f", OldNo: 1, NewNo: 1}, review.Line{Kind: 0, Text: "func a() {", OldNo: 2, NewNo: 2}, review.Line{Kind: 0, Text: "}", OldNo: 3, NewNo: 3}, review.Line{Kind: 1, Text: "func b() {", OldNo: 0, NewNo: 4}, review.Line{Kind: 1, Text: "}", OldNo: 0, NewNo: 5}}}}}}},
	"diff --git a/f.go b/f.go\nindex 3333333..2222222 100644\n--- a/f.go\n+++ b/f.go\n@@ -2,2 +2,4 @@\n func a() {\n }\n+func b() {\n+}\n":                                                                                                                                                                                                                                                                   review.Diff{Files: []review.File{review.File{Path: "f.go", OldPath: "f.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -2,2 +2,4 @@", Lines: []review.Line{review.Line{Kind: 0, Text: "func a() {", OldNo: 2, NewNo: 2}, review.Line{Kind: 0, Text: "}", OldNo: 3, NewNo: 3}, review.Line{Kind: 1, Text: "func b() {", OldNo: 0, NewNo: 4}, review.Line{Kind: 1, Text: "}", OldNo: 0, NewNo: 5}}}}}}},
	"diff --git a/internal/ui/model.go b/internal/ui/model.go\nindex 1111111..2222222 100644\n--- a/internal/ui/model.go\n+++ b/internal/ui/model.go\n@@ -10,4 +10,5 @@ func (m *Model) onKey() {\n \ta := 1\n-\tb := 2\n+\tb := 3\n+\tc := 4\n \treturn\n }\n":                                                                                                                                              review.Diff{Files: []review.File{review.File{Path: "internal/ui/model.go", OldPath: "internal/ui/model.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -10,4 +10,5 @@ func (m *Model) onKey() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 10, NewNo: 10}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 11, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 3", OldNo: 0, NewNo: 11}, review.Line{Kind: 1, Text: "\tc := 4", OldNo: 0, NewNo: 12}, review.Line{Kind: 0, Text: "\treturn", OldNo: 12, NewNo: 13}, review.Line{Kind: 0, Text: "}", OldNo: 13, NewNo: 14}}}}}}},
	"diff --git a/internal/ui/model.go b/internal/ui/model.go\nindex 1111111..2222222 100644\n--- a/internal/ui/model.go\n+++ b/internal/ui/model.go\n@@ -10,4 +10,5 @@ func (m *Model) onKey() {\n \ta := 1\n-\tb := 2\n+\tb := 3\n+\tc := 4\n \treturn\n }\ndiff --git a/new.txt b/new.txt\nnew file mode 100644\nindex 0000000..3333333\n--- /dev/null\n+++ b/new.txt\n@@ -0,0 +1,2 @@\n+fresh\n+file\n":  review.Diff{Files: []review.File{review.File{Path: "internal/ui/model.go", OldPath: "internal/ui/model.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -10,4 +10,5 @@ func (m *Model) onKey() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 10, NewNo: 10}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 11, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 3", OldNo: 0, NewNo: 11}, review.Line{Kind: 1, Text: "\tc := 4", OldNo: 0, NewNo: 12}, review.Line{Kind: 0, Text: "\treturn", OldNo: 12, NewNo: 13}, review.Line{Kind: 0, Text: "}", OldNo: 13, NewNo: 14}}}}}, review.File{Path: "new.txt", OldPath: "", Status: 1, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -0,0 +1,2 @@", Lines: []review.Line{review.Line{Kind: 1, Text: "fresh", OldNo: 0, NewNo: 1}, review.Line{Kind: 1, Text: "file", OldNo: 0, NewNo: 2}}}}}}},
	"diff --git a/internal/ui/model.go b/internal/ui/model.go\nindex 1111111..2222222 100644\n--- a/internal/ui/model.go\n+++ b/internal/ui/model.go\n@@ -10,4 +10,5 @@ func (m *Model) onKey() {\n \ta := 1\n-\tb := 2\n+\tb := 99\n+\tc := 4\n \treturn\n }\n":                                                                                                                                             review.Diff{Files: []review.File{review.File{Path: "internal/ui/model.go", OldPath: "internal/ui/model.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -10,4 +10,5 @@ func (m *Model) onKey() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 10, NewNo: 10}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 11, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 99", OldNo: 0, NewNo: 11}, review.Line{Kind: 1, Text: "\tc := 4", OldNo: 0, NewNo: 12}, review.Line{Kind: 0, Text: "\treturn", OldNo: 12, NewNo: 13}, review.Line{Kind: 0, Text: "}", OldNo: 13, NewNo: 14}}}}}}},
	"diff --git a/internal/ui/model.go b/internal/ui/model.go\nindex 1111111..2222222 100644\n--- a/internal/ui/model.go\n+++ b/internal/ui/model.go\n@@ -10,4 +10,5 @@ func (m *Model) onKey() {\n \ta := 1\n-\tb := 2\n+\tb := 99\n+\tc := 4\n \treturn\n }\ndiff --git a/new.txt b/new.txt\nnew file mode 100644\nindex 0000000..3333333\n--- /dev/null\n+++ b/new.txt\n@@ -0,0 +1,2 @@\n+fresh\n+file\n": review.Diff{Files: []review.File{review.File{Path: "internal/ui/model.go", OldPath: "internal/ui/model.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -10,4 +10,5 @@ func (m *Model) onKey() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 10, NewNo: 10}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 11, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 99", OldNo: 0, NewNo: 11}, review.Line{Kind: 1, Text: "\tc := 4", OldNo: 0, NewNo: 12}, review.Line{Kind: 0, Text: "\treturn", OldNo: 12, NewNo: 13}, review.Line{Kind: 0, Text: "}", OldNo: 13, NewNo: 14}}}}}, review.File{Path: "new.txt", OldPath: "", Status: 1, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -0,0 +1,2 @@", Lines: []review.Line{review.Line{Kind: 1, Text: "fresh", OldNo: 0, NewNo: 1}, review.Line{Kind: 1, Text: "file", OldNo: 0, NewNo: 2}}}}}}},
	"diff --git a/internal/ui/model.go b/internal/ui/model.go\nindex 1111111..2222222 100644\n--- a/internal/ui/model.go\n+++ b/internal/ui/model.go\n@@ -30,4 +31,5 @@ func (m *Model) onKey() {\n \ta := 1\n-\tb := 2\n+\tb := 3\n+\tc := 4\n \treturn\n }\ndiff --git a/new.txt b/new.txt\nnew file mode 100644\nindex 0000000..3333333\n--- /dev/null\n+++ b/new.txt\n@@ -0,0 +1,2 @@\n+fresh\n+file\n":  review.Diff{Files: []review.File{review.File{Path: "internal/ui/model.go", OldPath: "internal/ui/model.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -30,4 +31,5 @@ func (m *Model) onKey() {", Lines: []review.Line{review.Line{Kind: 0, Text: "\ta := 1", OldNo: 30, NewNo: 31}, review.Line{Kind: 2, Text: "\tb := 2", OldNo: 31, NewNo: 0}, review.Line{Kind: 1, Text: "\tb := 3", OldNo: 0, NewNo: 32}, review.Line{Kind: 1, Text: "\tc := 4", OldNo: 0, NewNo: 33}, review.Line{Kind: 0, Text: "\treturn", OldNo: 32, NewNo: 34}, review.Line{Kind: 0, Text: "}", OldNo: 33, NewNo: 35}}}}}, review.File{Path: "new.txt", OldPath: "", Status: 1, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -0,0 +1,2 @@", Lines: []review.Line{review.Line{Kind: 1, Text: "fresh", OldNo: 0, NewNo: 1}, review.Line{Kind: 1, Text: "file", OldNo: 0, NewNo: 2}}}}}}},
	"diff --git a/x.go b/x.go\nindex 1111111..2222222 100644\n--- a/x.go\n+++ b/x.go\n@@ -1,3 +1,3 @@\n }\n-old\n+new\n }\n":                                                                                                                                                                                                                                                                                 review.Diff{Files: []review.File{review.File{Path: "x.go", OldPath: "x.go", Status: 0, Binary: false, Hunks: []review.Hunk{review.Hunk{Header: "@@ -1,3 +1,3 @@", Lines: []review.Line{review.Line{Kind: 0, Text: "}", OldNo: 1, NewNo: 1}, review.Line{Kind: 2, Text: "old", OldNo: 2, NewNo: 0}, review.Line{Kind: 1, Text: "new", OldNo: 0, NewNo: 2}, review.Line{Kind: 0, Text: "}", OldNo: 3, NewNo: 3}}}}}}},
}

// parse returns raw's pre-parsed diff, as internal/review's parse helper
// would have.
func parse(t *testing.T, raw string) review.Diff {
	t.Helper()
	d, ok := parsed[raw]
	if !ok {
		t.Fatalf("no pre-parsed diff for this input; regenerate with GEN_FIXTURES=1 (see parsed_generate_test.go in internal/infra/gitdiff)")
	}
	return d
}
