# This file was generated by GoReleaser. DO NOT EDIT.
cask "omatty" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "b7c096a524d0e2fc9574864dd35de7ea96878346b7a5a458a2080f16f2ebed7d"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "90fabec264f30999ee0ca6ed0bb2a0aa110ae22475cb321e28a76b809ee45de9"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce332fac8d55a73da1d2e64bf617fd3a24ad01a5a9f9383bc64390f4f647e25b"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1eb51410a768fbe2d008fc386ad57c8a030a96e8577e23c3b17b9ba6ddcfb0f7"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omatty"
  desc "Terminal ADE: multiple projects and parallel Claude Code sessions in one TUI"
  homepage "https://github.com/WilsonSousajr/omatty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omatty"

  # No zap stanza required
end
